name: CD - Heroku

on:
  push:
    branches:
      - master
      - release-*

jobs:
  deploy:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.API_KEY_HEROKU}}
          heroku_app_name: ${{secrets.NAME_REPO_HEROKU}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL_HEROKU}}
